### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [bennypowers/lit-apollo#1]
Please add support of GraphQL real-time subscriptions (updates).

**Comment by FluorescentHallucinogen** [comment]
I'm a web developer of https://gdezerno.ru progressive web app (PWA) built using web components (Polymer) on front-end and Firebase on back-end.

I like Firebase, because data is synced across all clients in realtime. But Firebase has some downsides: it doesn't support complex database queries, it can not be deployed on my own server.

Now I'm researching the possibility of migrating back-end from Firebase to Prisma (https://prisma.io). It uses OpenCRUD GraphQL API (https://www.prisma.io/features/graphql-api/).

See https://blog.graph.cool/graphql-vs-firebase-496498546142 for more info.

But I'm worrying about the integration of Polymer with GraphQL. Now I use PolymerFire (https://webcomponents.org/element/firebase/polymerfire) to integrate Polymer with Firebase.

But if I migrate, I will need a replacement of PolymerFire webcomponents.

I plan to use GraphQL client-side subscription on front-end and [GraphQL server-side subscription](https://www.prisma.io/docs/reference/server_side-subscriptions/overview-to1ahf0ob6) instead of [Cloud Functions for Firebase database events triggers](https://firebase.google.com/docs/functions/) on back-end.

**Comment by bennypowers** [comment]
It would be up to the app author to set up and bundle `subscriptions-transport-ws`. Our components would just expose APIs on the client as web component base classes.

**Comment by FluorescentHallucinogen** [comment]
Should I use `ApolloQuery` class for subscriptions?

**Comment by FluorescentHallucinogen** [comment]
@bennypowers Could you please show (small code sample) how to use your base classes with subscriptions?   Should I use [apollo-link-ws](https://www.npmjs.com/package/apollo-link-ws) too?

**Comment by bennypowers** [comment]
I haven't tried yet. If you already have apollo-link-ws set up in your client build, try sending a subscription query through an ApolloQuery element. NO clue if it will work and i suspect it wont

**Comment by FluorescentHallucinogen** [comment]
@bennypowers 
> NO clue if it will work and i suspect it wont

This is not good. Subscriptions is one of the most important features why developers use Apollo Client (alongside with cache).

**Comment by bennypowers** [comment]
Did you give it a try? I'm curious to know what happened.

**Comment by FluorescentHallucinogen** [comment]
It's not possible to use subscriptions in `ApolloQuery` due to `Error: Must contain a query definition.` error.

It can be dirty fixed by changing `client.watchQuery` to `client.subscribe` in https://github.com/bennypowers/lit-apollo/blob/master/apollo-query.js#L279.

A few months ago, I added subscriptions (along with file uploads) support to [polymer-apollo-client](https://github.com/reach-digital/polymer-apollo-client).

PTAL [here](https://raw-dot-custom-elements.appspot.com/reach-digital/polymer-apollo-client/2.4.1/polymer-apollo-client/demo/full-demo.html) to see it in action.

What about `ApolloSubscription` class and `<apollo-subscription>` custom element similar to my [`<graphql-subscription>`](https://github.com/reach-digital/polymer-apollo-client/blob/master/graphql-subscription.html)? :wink:

**Comment by bennypowers** [comment]
Yeah looks like now's the time to start on that implementation. If what you say is correct, it may be as straightforward as extending ApolloQuery and implementing `subscribe` method as above. I'll look into this shortly.

**Comment by bennypowers** [comment]
@FluorescentHallucinogen  see https://warm-lowlands-46449.herokuapp.com/
