### ISSUE TITLE
Webpack configuration

### ISSUE THREAD

**Issue by aadamsx** [bennypowers/lit-apollo#13]
I'm looking at using lit-html, lit-apollo, & apollo-client, but of course need to use webpack.  But I've never used webpack.  Does anyone have a working config they could drop that will help?

Thanks

**Comment by bennypowers** [comment]
I've used rollup with lit-apollo as such:

```js
export default {
  input: 'src/index.js',
  output: {
    file: 'bundle.js',
    format: 'es',
    sourcemap: true,
  },
  watch: {
    include: ['src/**/*.js'],
  },
  plugins: [
    resolve({ browser: true, module: true, jsnext: true, preferBuiltins: true }),
    commonjs(),
  ]
}
```

YMMV

**Comment by bennypowers** [comment]
I'm going to close this, since it seems the proposed solution is working for you. Feel free to reopen if you need to.
