### ISSUE TITLE
Inline query scripts syntax highlighting

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [bennypowers/lit-apollo#21]
This is not an issue with `lit-apollo` itself.

@bennypowers Do you know the IDE plugins that support syntax highlighting for inline query scripts?

```html
<apollo-query data="{{data}}" variables="[[variables]]">
  <script type="application/graphql">
    query User($id: ID!)
      user(id: $id) {
        name
        picture
      }
    }
  </script>
</apollo-query>
```

I'm personally interested in the plugin for VSCode.

**Comment by bennypowers** [comment]
[atom supports graphql script tags](https://github.com/atom/language-html/pull/191). I'm sure a similar PR could be prepared for VS Code. 
Thanks for the issue :D

**Comment by FluorescentHallucinogen** [comment]
@bennypowers Could you please prepare a similar PR for VSCode?

Yesterday, I've tried to convert [your changes](https://github.com/atom/language-html/pull/191/files) from CSON to JSON and insert it to https://github.com/Microsoft/vscode/blob/master/extensions/html/syntaxes/html.tmLanguage.json, but, unfortunately, it has not worked.

**Comment by bennypowers** [comment]
I'm not a VSCode user, and don't know their codebase either :/
