### ISSUE TITLE
README: update "Usage"

### ISSUE THREAD

**Issue by LasaleFamine** [bennypowers/lit-apollo#7]
I think there is an error on the usage example: the imported `ApolloQuery` seems from a wrong path.
Also I think should be added a reference for the `client` prop.

What do you think about this example? Ex:
```js
<script type="module">
  import gql from 'graphql-tag';
  import ApolloClient from 'apollo-boost';
  import {ApolloQuery} from 'lit-apollo';

  // Create the apollo client
  const apolloClient = new ApolloClient({
	uri: 'https://your.graphql.server'
  });

  class MyConnectedElement extends ApolloQuery {
    _render({ data: { helloWorld }, loading, error, networkStatus }) {
      return (
          loading ? html`
            <what-spin></what-spin>`
        : error ? html`
            <h1>😢 Such sad, very error!</h1>
            <div>${error.message}</div>`
        : html`
            <div>${helloWorld.greeting}, ${helloWorld.name}</div>`
      );
     }

     constructor() {
       super();
       this.client = apolloClient;
       this.query = gql`query { helloWorld { name, greeting } }`;
     }
  };
  customElements.define('connected-element', MyConnectedElement)
</script>
```

Of course the `window` option must be documented but I think this is much more handy.

Side question: do you have some plan to document all the props and API exposed by the elements? Maybe it's worth to open an issue about documenting this also outside the README (maybe a GHPage with a small site).

**Comment by bennypowers** [comment]
WRT method and property documentation, I went through earlier today and documented aaaalmost everything. You can see the result on [webcomponents.org](https://www.webcomponents.org/element/lit-apollo/classes/ApolloQuery). We could host a GH page (or a GL page when we move there) that shows the polymer analyzer results, as well.
